from hackathon_science.cloud_client import CloudClient
import re
from hackathon_science.utils import call_llm

# ---------------------------------------------------------------------------
# Ecosystem paper fetching
# ---------------------------------------------------------------------------

RELEVANT_TAGS = ["flow-of-options","multi-agent", "voting", "scaling", "ensemble", "reasoning", "falsification", "bayesian", "quality-diversity", "active-learning", "thompson-sampling", "hypothesis-falsification"]

def fetch_ecosystem_papers() -> list[dict]:
    """Fetch relevant papers from the ecosystem via API."""
    try:
        client = CloudClient()
        all_papers = client.list_papers(page_size=50)

        relevant = []
        for summary in all_papers:
            paper_id = summary.get("id", "")
            title = summary.get("title", "").lower()
            tags = [t.lower() for t in summary.get("tags", [])]

            if summary.get("team_id") == "super-crime":
                continue

            is_relevant = (
                "flow-of-options" in title or
                "multi-agent" in title or
                "voting" in title or
                "scaling" in title or
                "ensemble" in title or
                "diversity" in title or
                "disagreement" in title or
                "bayesian" in title or
                any(tag in tags for tag in RELEVANT_TAGS)
            )
            if is_relevant and paper_id:
                full_paper = client.get_paper(paper_id)
                relevant.append(full_paper)
                if len(relevant) >= 5:
                    break
        return relevant
    except Exception:
        return []


# ---------------------------------------------------------------------------
# LLM response helpers
# ---------------------------------------------------------------------------

def llm_text(response: dict) -> str:
    """Safely extract text from a call_llm response dict."""
    output = response.get("output", {}).get("message", {}).get("content", [])
    return output[0].get("text", "").strip() if output else ""


def extract_score(text: str) -> int:
    """Extract integer score from 'SCORE = NUMBER' pattern."""
    match = re.search(r'SCORE\s*=\s*(\d+(?:\.\d+)?)', text)
    return int(float(match.group(1))) if match else 0


def extract_code(text: str) -> str:
    """Extract only the code from an LLM response, stripping surrounding prose.
    Looks for a fenced ```...``` block first; falls back to the raw text."""
    match = re.search(r'```(?:python)?\n(.*?)```', text, re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def has_error(output: str) -> bool:
    """Return True if the output of run_code contains signs of a runtime error."""
    _ERROR_SIGNALS = (
        "error", "traceback", "exception", "exit code 1",
        "syntaxerror", "indentationerror", "nameerror", "typeerror", "valueerror",
    )
    return any(sig in output.lower() for sig in _ERROR_SIGNALS)


# ---------------------------------------------------------------------------
# Paper scoring
# ---------------------------------------------------------------------------

META_CONTEXT = (
    "META-CONTEXT: this paper was generated by an agentic model as part of a "
    "hackathon event with the goal of generating credible scientific papers that "
    "extend on the prompt topic."
)


def score_paper(
    paper: dict,
    problem_domain: str,
    model_id: str,
) -> tuple[int, dict] | None:
    """Score a single paper dict for relevance to problem_domain.

    Args:
        paper:          Paper dict with at least 'title' and 'abstract'/'introduction'.
        problem_domain: The research domain string to score against.
        model_id:       LLM model ID to use for scoring.

    Returns:
        (score, result_dict) or None if the paper has no usable content.
    """
    title   = paper.get("title",    "")
    snippet = paper.get("abstract", paper.get("introduction", ""))[:300]
    if not title and not snippet:
        return None

    prompt = (
        f"{META_CONTEXT} "
        f"Assess this title and abstract for relevance to topic '{problem_domain}'. "
        f"Return a number from 0-10 with 10 being highly relevant. "
        f"Return in format SCORE=NUMBER (no brackets). "
        f'Title: "{title}", Abstract: "{snippet}"'
    )
    out   = call_llm(
        messages=[{"role": "user", "content": [{"text": prompt}]}],
        model_id=model_id,
    )
    score = extract_score(llm_text(out))
    print(f"  [{score:>2}] {title[:80]}")
    return (score, {
        "title":   title,
        "snippet": snippet,
        "url":     paper.get("url", ""),
        "_paper":  paper,
    })